version: 2.1

orbs:
  browser-tools: circleci/browser-tools@2.3.1

workflows:
  version: 2
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:22.18.0
    resource_class: medium+
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm ci
      - run: npm run lint
      - run: npm test
