version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

workflows:
  version: 2
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:16.19.0-browsers
    resource_class: medium+
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npx ember try:one embroider-safe
