version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.3.0

workflows:
  version: 2
  main:
    jobs:
      - test
      - try-scenarios:
          matrix:
            parameters:
              try-scenario:
                - embroider-safe
                - embroider-optimized

jobs:
  test:
    docker:
      - image: cimg/node:16.19.0-browsers
    resource_class: medium+
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm ci
      - run: npm run lint
      - run: npm test

  try-scenarios:
    parameters:
      try-scenario:
        type: string
    docker:
      - image: cimg/node:16.19.0-browsers
    resource_class: medium+
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run: npm ci
      - run: npx ember try:one << parameters.try-scenario >>
